export const ON_NEW_CHAT_MESSAGE = "onNewChatMessage"
export const ON_UPDATE_CHAT_MESSAGE = "onUpdateChatMessage"
export const ON_DELETE_CHAT_MESSAGE = "onDeleteChatMessage"
export const ON_NEW_CHANNEL = "onNewChannel"
export const ON_DELETE_CHANNEL = "onDeleteChannel"